/* eslint-disable import/no-anonymous-default-export */
const COUNT_CHAN='COUNT_CHAN'
const STUDY_UPDATE='STUDY_UPDATE'
const GET_QQ_MUSIC='GET_QQ_MUSIC'
const SUBMNI_LGOIN='SUBMNI_LGOIN'
const USER_INFO='USER_INFO'
const ARTICLE_LIST='ARTICLE_LIST'
const ARTICLE_CATE='ARTICLE_CATE'
const LEAVE_LIST='LEAVE_LIST'
const WRITE_LEAVE_LIST='WRITE_LEAVE_LIST'
const ARTICLE_ADD='ARTICLE_ADD'
const USER_LIST='USER_LIST'

export default{
    COUNT_CHAN,
    STUDY_UPDATE,
    GET_QQ_MUSIC,
    SUBMNI_LGOIN,
    USER_INFO,
    ARTICLE_LIST,
    ARTICLE_CATE,
    LEAVE_LIST,
    WRITE_LEAVE_LIST,
    ARTICLE_ADD,
    USER_LIST
}